### ISSUE TITLE
外部のライブラリとプロジェクト用のファイルの見分けがつきにくい

### ISSUE THREAD

**Issue by tsukune-ch** [CranberryProject/Cranberry#3]
外部のライブラリとプロジェクト用のファイルやディレクトリが同じ階層に入っているので見分けがつきにくいです。
なので外部のライブラリは外部のライブラリと分かるような名前のディレクトリを作ってそこにまとめると可視性が高くなると思うのですがどうでしょうか。

**Comment by katabamia** [comment]
確かに他のサービスでもそのようにしているのは見かけます。
可読性のためにも採用したいのですがPHPライブラリ以外のCSS、js等をどのようにするかが問題となりそうです。

**Comment by tsukune-ch** [comment]
CSSやJSなどの外部ライブラリは、各々が格納されているcss/やjs/のディレクトリの中にvendorというディレクトリを作成して、その中にまとめてみるのはどうでしょう。

**Comment by katabamia** [comment]
```
/
|
asset
    |-- css
    |    |-- vendor
    |    |      |-- something.css
    |    |
    |    |-- another.css
    |
    |-- js
         |-- vendor
         |      |-- something.js
         |
         |-- another.js
```
のような形と
```
/
|
asset
    |-- css
    |    |-- another.css
    |
    |-- js
    |    |-- another.js
    |
    |-- vendor
         |-- something.css
         |-- something.js
```
のような形だとどちらのほうが管理しやすいですかね。
(2番目の方だと vendor/css, vemdor/js と分けてもいいかもしれない)

**Comment by tsukune-ch** [comment]
2番目の方が好みです〜

**Comment by katabamia** [comment]
Commit: df9c509d008da42f5ef4dbbe994dba0df60303c3 においてファイル構造を変更してみました。
これでよければCloseしてもらえるとうれしいです。
