### ISSUE TITLE
CIツール等の利用について

### ISSUE THREAD

**Issue by katabamia** [CranberryProject/Cranberry#4]
CIツール等を利用したことがないため、どのようなものを利用すればよいか分からない状態です。
今現在、CircleCI, TravisCIをテスト用として導入しようとしているのですが、設定の記述法がよくわからず `Build: Falling` の状態です。

なにかおすすめのCIツール等や設定の記述がありましたらコメントでお教えいただけるとありがたいです。

**Comment by tsukune-ch** [comment]
CircleCIとTravisCIは両方導入する必要はないと思うので、OSSのプロジェクトだと無料で使うことのできるTravisCIを使うのが良いと思います。
とりあえず、TravisCIでlintだけを実行する設定を書いてPR送ってみました。
