### ISSUE TITLE
Editor real time preview

### ISSUE THREAD

**Issue by katabamia** [CranberryProject/Cranberry#6]
## 目的

Editor.phpをリアルタイム更新に対応させる

## TaskList

- CodemirrorのEditorのテキストが変更された際にCodemirrorのsaveメソッドを呼び出す

## Closeの定義

codemirrorを用いた状態でmarkdownのリアルタイム更新に対応させること

## 参考

特になし。

## その他

現在Vue.jsおよびmarked.jsを用いているが、その他に良い方法があれば実装したい。

**Comment by katabamia** [comment]
Javascriptに強い @SnO2WMaN くん頼んだ(他力本願

**Comment by SnO2WMaN** [comment]
X(
